### ISSUE TITLE
Keyed Nodes

### ISSUE THREAD

**Issue by kesne** [patrick-steele-idem/morphdom#3] opened 2015-08-15 21:06 UTC
I think it would be beneficial to have some way to have morphdom handle keys similar to how they are handled in virtual-dom (https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/README.md#key).

Maybe a non-standard HTML attribute (such as `key="someKey"`) could be used along with the tagName to determine if a node is identical?

I'm happy to make a PR for whatever you're are happy with, I just think something like this would be helpful!

**Comment by patrick-steele-idem** [comment] 2015-08-15 21:26
Hi @kesne, morphdom uses the "id" attribute as the "key" by design. That is, morphdom works best if there are stable IDs for HTML elements and it will take extra steps to match up elements with matching IDs that are found in both the old DOM and the new DOM. Is there something else that you think is still missing?

**Comment by kesne** [comment] 2015-08-15 22:04
Ah, probably would have been good to read through the source before making an issue! My mistake.

I guess the only callout is that the benefit of a key design is that keys can be re-used in two different trees that you're running through morphdom, whereas IDs need to be absolutely unique.

**Comment by patrick-steele-idem** [comment] 2015-08-15 22:20
True. With [Marko Widgets](https://github.com/marko-js/marko-widgets) we have a strategy for ensure IDs are always unique by prefixing IDs with the ID of the parent widget. That trick has worked really well for Marko Widgets. For rendering lists of items we recommend using the index of the current iteration prefixed with the ID of the parent widget as the unique ID. If you have any other thoughts or suggestions please share!

**Comment by kesne** [comment] 2015-08-15 22:39
Yeah it's not really an issue with my use cases, I just thought I would call it out.

Feel free to close the issue if you're fine with the state of things.

**Comment by patrick-steele-idem** [comment] 2015-08-15 22:56
Sounds good. I will close this issue, but we can always reevaluate later. Thanks.

**Closed by patrick-steele-idem** 2015-08-15 22:56 UTC
